name: Update Sileo Repo

on:
  push:
    paths:
      - 'debs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Dòng quan trọng nhất để sửa lỗi 403:
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2

      - name: Generate Packages & Release
        run: |
          rm -f Packages Packages.bz2 Release
          dpkg-scanpackages -m ./debs > Packages
          bzip2 -fk Packages
          echo "Origin: Minstool Repo" > Release
          echo "Label: Minstool" >> Release
          echo "Suite: stable" >> Release
          echo "Version: 1.0" >> Release
          echo "Codename: ios" >> Release
          echo "Architectures: iphoneos-arm64" >> Release
          echo "Components: main" >> Release
          echo "Description: Kho tweak cho RootHide" >> Release

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.bz2 Release
          git commit -m "Update repo index" || exit 0
          git push
