name: Update Sileo Repo
on:
  push:
    paths:
      - 'debs/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2

      - name: Generate Packages & Release
        run: |
          rm -f Packages Packages.bz2 Release
          dpkg-scanpackages -m ./debs > Packages
          bzip2 -fk Packages
          {
            echo "Origin: Minstool Repo"
            echo "Label: Minstool"
            echo "Suite: stable"
            echo "Version: 1.0"
            echo "Codename: ios"
            echo "Architectures: iphoneos-arm64"
            echo "Components: main"
            echo "Description: Kho tweak cho RootHide"
          } > Release

      - name: Generate Packages & Release
        run: |
          rm -f Packages Packages.bz2 Release
          
          # Lệnh quét kèm theo điều kiện bỏ qua file lỗi
          # Chúng ta dùng "|| true" để nếu 1 file lỗi thì nó vẫn chạy tiếp
          dpkg-scanpackages -m ./debs /dev/null > Packages || true
          
          # Kiểm tra nếu file Packages trống rỗng
          if [ ! -s Packages ]; then
            echo "Canh bao: File deb bi loi hoac khong tim thay file hop le!"
          fi
          
          bzip2 -fk Packages
          
          {
            echo "Origin: Minstool Repo"
            echo "Label: Minstool"
            echo "Suite: stable"
            echo "Version: 1.0"
            echo "Codename: ios"
            echo "Architectures: iphoneos-arm64 iphoneos-arm64e"
            echo "Components: main"
            echo "Description: Kho tweak cho RootHide"
          } > Release
